notifications:
    email: false
language: python
python:
    - "3.6"
before_install:
    - git clone https://$CI_USER_TOKEN@github.com/UCSD-Product-Engineering/assignment0_answer.git
    - cp assignment0_answer/test.py test.py
    - touch __init__.py
script: 
    - python test.py
